# services missing: nodejs, nginx
version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=cccc
    ports:
      - '3306:3306'
  redis:
    image: redis
    ports:
      - '6379:6379'